spring:
  application:
    name: EmployeeHub
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB:springboot-employeehub-api}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: ${APP_PROFILE:local}
app:
  baseUrl: ${APP_BASE_URL:http://localhost:8080}
  jwt:
    secret: ${JWT_SECRET}
    accessSeconds: ${ACCESS_TOKEN_SECONDS}
    refreshSeconds: ${REFRESH_TOKEN_SECONDS}
    issuer: ${TOKEN_ISSUER}
    accessCookieName: access_token
    refreshCookieName: refresh_token

