spring:

  application:
    name: employeehub

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # DATABASE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB:springboot-employeehub-api}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  # PROFILES
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # RABBITMQ
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  # FLYWAY
  # naming convention: V{version}__{description}.sql
  flyway:
    enabled: true
    locations: classpath:db/migration
#   Needed if have an existing database
#    baseline-version: 1
#    baseline-on-migrate: true

# APP SPECIFIC
app:
  baseUrl: ${APP_BASE_URL:http://localhost:8080}
  jwt:
    secret: ${JWT_SECRET}
    accessSeconds: ${ACCESS_TOKEN_SECONDS}
    refreshSeconds: ${REFRESH_TOKEN_SECONDS}
    issuer: ${TOKEN_ISSUER}
    accessCookieName: access_token
    refreshCookieName: refresh_token

# AWS
aws:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    presignExpireMinutes: ${S3_PRESIGN_EXPIRE_MINUTES:3}

# DOCUMENT
document:
  maxSizeBytes: ${DOCUMENT_MAX_SIZE:10485760}
  allowedContentTypes: application/pdf,image/png,image/jpeg,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document

